### ISSUE TITLE
Is it suppose to show 2 video streams on the same tab?

### ISSUE THREAD

**Issue by rafasashi** [nielsbaloe/webrtc-php#1]
Hello nielsbaloe,

Thanks for sharing this code.

I am testing it and I can see one file created when I start the webcam on one side but when I start the webcam on the other side the file is removed and I dont see both streams, only myself.

Am I missing anything?

**Comment by nielsbaloe** [comment]
Hi,

Well, when there is communication going on between both of them, you should see two files being created and deleted continuously every few seconds. If you press F12 on both sides and look in the javascript log, does it say what is wrong? It looks like the second screen you start can't make a connection somehow. And, can you share it?

It would be nice to keep this code working, to let it be served for doing webRTC on cheap hosting.

Best,

Niels Gorisse
https://www.verbindendecommunicatie.com
https://www.strohplatz.com

________________________________
Van: Raphaël Dartigues <notifications@github.com>
Verzonden: zondag 23 juni 2019 08:11
Aan: nielsbaloe/webrtc-php
CC: Subscribed
Onderwerp: [nielsbaloe/webrtc-php] Is it suppose to show 2 video streams on the same tab? (#1)


Hello nielsbaloe,

Thanks for sharing this code.

I am testing it and I can see one file created when I start the webcam on one side but when I start the webcam on the other side the file is removed and I dont see both streams, only myself.

Do I miss anything?

**Comment by mmethner** [comment]
Hi Niels,

I also tried the code and can see my own video.
When I connect to the same url on different computers I also see the computers camera, but not both of them at the same time. The browser console does not show any error messages. It prints only "sending ws.send: client-call" on both computers.

Best regards 
Mathias

**Comment by mmethner** [comment]
Hi Niels, Hi rafasashi,

the reason it did not work on my setup was having the folder not writable for nginx.
chmod the folder like you described fixed the issue.

Thanks for sharing your setup
Mathias

**Comment by nielsbaloe** [comment]
Hi Matthias,
I am on vacation so I am currently a bit slow with replying. Great that it worked out, I hope you can use it as starting point for a great project!
Best,
Niels
