### ISSUE TITLE
Voice Call Doesn't Work

### ISSUE THREAD

**Issue by bjesua** [nielsbaloe/webrtc-php#10]
Great Project, i just have one question, why doesn't it work with voice call?

**Comment by xuzhousoft09** [comment]
Hello,
Did you mean can't hear the voice?

I changed: 
video id="localVideo" autoplay="true" muted="muted"

to:
video id="localVideo" autoplay="true"

So that I could hear my voice.

**Comment by bjesua** [comment]
Thank you bro, i made the changes, but still not working for me.

**Comment by bjesua** [comment]
Thank you bro

**Comment by nielsbaloe** [comment]
Enable javascript line  //  audio: true,
