### ISSUE TITLE
Peer 2 Peer connection not happening

### ISSUE THREAD

**Issue by SannanOfficial** [nielsbaloe/webrtc-php#12]
I am using this on a website with a valid SSL certificate and force HTTPS, I have pasted the exact files on my website without doing anything else, but when I look at the Javascript console the 406 server status error which means not acceptable.

How can I fix this?

**Comment by nielsbaloe** [comment]
Hi,

Hmm, that should work pretty fine. Can you copy-paste your javascript console?


Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Sannan <notifications@github.com>
Verzonden: donderdag 2 juli 2020 02:08
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] Peer 2 Peer connection not happening (#12)


I am using this on a website with a valid SSL certificate and force HTTPS, I have pasted the exact files on my website without doing anything else, but when I look at the Javascript console the 406 server status error which means not acceptable.

How can I fix this?

**Comment by SannanOfficial** [comment]
The only thing I get in the javascript console is this
 Failed to load resource: the server responded with a status of 406 ()

**Comment by nielsbaloe** [comment]
Hi,

OK, and what URL does it show. Which URL has the 406? Can you give the full log please? Thanks,

Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Sannan <notifications@github.com>
Verzonden: vrijdag 3 juli 2020 01:09
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Peer 2 Peer connection not happening (#12)


The only thing I get in the javascript console is this
Failed to load resource: the server responded with a status of 406 ()

**Comment by SannanOfficial** [comment]
my whole console only says this,

sending ws.send: client-call
/virtualRoom/serverPost.php?unique=195016:1 Failed to load resource: the
server responded with a status of 406 ()
Error sending to server with message: {"event":"client-call","data":null}
EventSource finished loading: GET "<URL>".

It does display the camera on my side but does not let me connect to the
other person.

**Comment by nielsbaloe** [comment]
Hi,

Hmmm. I do not have a clue. Seems like something with php is going wrong...
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406
if you load your full url ( your /virtualRoom/serverPost.php?unique=... ) in a browser tab, you should see a normal reply.
That serverPost is just a regular PHP file, so you should get some regular response.

Can you add " echo 'olah';die(); " as first line in the serverPost.php file? You should then at least get it working.
Now you can slowly add some more.

Did you give your folder read/write rights?


Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Sannan <notifications@github.com>
Verzonden: vrijdag 3 juli 2020 14:29
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Peer 2 Peer connection not happening (#12)


my whole console only says this,

sending ws.send: client-call
/virtualRoom/serverPost.php?unique=195016:1 Failed to load resource: the
server responded with a status of 406 ()
Error sending to server with message: {"event":"client-call","data":null}
EventSource finished loading: GET "<URL>".

It does display the camera on my side but does not let me connect to the
other person.

**Comment by SannanOfficial** [comment]
Yes, I added the following PHP line of code as the first line and I got a
normal reply of "olah" as planned but still the p2p connection won't work
If my hosting and stuff matters, here are some little details:

I have got a Hostgator hatchling package with a Cpanel shared hosting with
a Free SSL certificate.

**Comment by nielsbaloe** [comment]
Hi,

Ah that is great. Thank you can shift that olah-line more down to in between some lines, further and further down, trying to find the problem.

Did you chmod your folder? I think it is a read/write-issue.



Best,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Sannan <notifications@github.com>
Verzonden: maandag 6 juli 2020 12:34
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Peer 2 Peer connection not happening (#12)


Yes, I added the following PHP line of code as the first line and I got a
normal reply of "olah" as planned but still the p2p connection won't work
If my hosting and stuff matters, here are some little details:

I have got a Hostgator hatchling package with a Cpanel shared hosting with
a Free SSL certificate.

**Comment by SannanOfficial** [comment]
I am moving the olah line, but I am 100% sure that it is not the folder
read/write issue I have checked it and the permission seems to be 0755.
