### ISSUE TITLE
any future updates?

### ISSUE THREAD

**Issue by gumuruhsspj** [nielsbaloe/webrtc-php#16]
i wonder if there's any updates......

**Comment by nielsbaloe** [comment]
Hi,

There are no updates, it is a starting point for other projects, so I will only update the project when I do something with it. It is not the intention to keep it updated myself, you are invited to do that yourself!

With regards,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Gumuruh <notifications@github.com>
Verzonden: zondag 15 november 2020 15:41
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] any future updates? (#16)


i wonder if there's any updates......
