### ISSUE TITLE
room generate help

### ISSUE THREAD

**Issue by bodispatrik** [nielsbaloe/webrtc-php#17]
Hi, how could you create more chat rooms with this code? Maybe I can ask for your help with this problem?

**Comment by nielsbaloe** [comment]
Hi,

Well, you would have to create a connection between everyone seperately. Unfortunately I do not have the time to work that out, I am sorry!


Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: bodispatrik <notifications@github.com>
Verzonden: zaterdag 21 november 2020 19:50
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] room generate help (#17)


Hi, how could you create more chat rooms with this code? Maybe I can ask for your help with this problem?

**Comment by bodispatrik** [comment]
Thank you very much for your quick reply! Not exactly that, but in the end I managed to solve the problem
