### ISSUE TITLE
use this with data channel\

### ISSUE THREAD

**Issue by realrecordzLab** [nielsbaloe/webrtc-php#2]
Hi. Is it possible to use this for a real time text chat using data channel?
I want to separate the code in different files, any help to implement data channel will be appreciated.

**Comment by nielsbaloe** [comment]
Hi,

Yes for sure this is possible for a data channel.

However, if it is just for text chat, then you can also throw away everything webrtc related and just use the SSE or websockets. For just text, do not use webrtc at all. Just SSE or websockets!

Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: realrecordzLab <notifications@github.com>
Verzonden: donderdag 25 juli 2019 17:11
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] use this with data channel\ (#2)


Hi. Is it possible to use this for a real time text chat using data channel?
I want to separate the code in different files, any help to implement data channel will be appreciated.

**Comment by realrecordzLab** [comment]
@nielsbaloe 
> However, if it is just for text chat, then you can also throw away everything webrtc related and just use the SSE or websockets. For just text, do not use webrtc at all. Just SSE or websockets!

Supposing that I'm using the SSE code you've created, can you show me a sample of the data channel implementation?

**Comment by nielsbaloe** [comment]
I'm afraid I do not have time for that. However you can easily find examples about SSE - or if you have commandline access to PHP or unlix, try websockets. There are plenty of examples out there that will work for you. If you're really stuck for days and days on, I can make a half an hour to help you out, but right now I'm glad to have an half hour of time for myself 😉 Super good luck.

Have fun!,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: realrecordzLab <notifications@github.com>
Verzonden: vrijdag 26 juli 2019 20:19
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] use this with data channel\ (#2)


@nielsbaloe<https://github.com/nielsbaloe>

However, if it is just for text chat, then you can also throw away everything webrtc related and just use the SSE or websockets. For just text, do not use webrtc at all. Just SSE or websockets!

Supposing that I'm using the SSE code you've created, can you show me a sample of the data channel implementation?

**Comment by pwFoo** [comment]
Data Channel works p2p instead via server as see, but could be easier...

Is it possible to add data channel runtime? Or start with data channel and add audio / video during webrtc (data) session?

**Comment by nielsbaloe** [comment]
Hi,

Thanks for the suggestion to use the muted tag. I added it.

I have no idea how the data transfer works. I guess you can initialise it at the same time the audio and video is negotiated and started....

Best,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: pwFoo <notifications@github.com>
Verzonden: donderdag 1 augustus 2019 23:28
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] use this with data channel\ (#2)


Data Channel works p2p instead via server as see, but could be easier...

Is it possible to add data channel runtime? Or start with data channel and add audio / video during webrtc (data) session?
