### ISSUE TITLE
Help on adding room functionality!!! please

### ISSUE THREAD

**Issue by Ajinx1** [nielsbaloe/webrtc-php#20]
Hello, great work making webtrc without websockets thanks for that. i know you said you left out the room functionality on purpose but i will like to understand how to actualize it, i need it please how do i go about it.
P.S. the room is just for two users each, thanks.

**Comment by nielsbaloe** [comment]
Hi,

I really can not help you there, I never implemented that. The room functionality now works, so duplicate that between every pair of users and you have your rooms. You do not need to change anthing if you want 2 users per room. Just use this script for every room.

I decided it is too hard to make, or at least: to keep it working. The specs change and I do not have time to maintain that. So I generate links to jitsi and use that instead. Maybe that works for you  too.

Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Ayotola Ajisola <notifications@github.com>
Verzonden: zaterdag 5 december 2020 11:26
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] Help on adding room functionality!!! please (#20)


Hello, i know you said you left out the room functionality on purpose but i will like to understand how to actualize it, i need it please how do i go about it.
P.S. the room is just for two users each, thanks.

**Comment by Ajinx1** [comment]
alright thanks.
