### ISSUE TITLE
Are the STUN servers required?

### ISSUE THREAD

**Issue by flatsiedatsie** [nielsbaloe/webrtc-php#21]
I noticed some third party URL's in the code, including a server from Google.

Is it possible to use this concept without connecting to third party servers at any time?

**Comment by nielsbaloe** [comment]
Hi,

Yes you can. You can easily search and set up such servers yourself, the easiest with node.js I guess. Ask Google, you'll find it in a heartbeat.

Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: flatsiedatsie <notifications@github.com>
Verzonden: maandag 14 december 2020 21:55
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [nielsbaloe/webrtc-php] Are the STUN servers required? (#21)


I noticed some third party URL's in the code, including a server from Google.

Is it possible to use this concept without connecting to those servers?
