### ISSUE TITLE
Question about SSE

### ISSUE THREAD

**Issue by pwFoo** [nielsbaloe/webrtc-php#4]
I like the solution with SSE and try to check what's possible and what not with SSE. Websockets would need "better" webspaces with possibility to run a process for websocket on a different (high) port?

Is it right that it isn't possible to send some events only to a specific user? All "subscribed" / connected users get all messages and filtering client side?

Or is it possible to distinguish between users by php session id or something else to send filtered data?

**Comment by pwFoo** [comment]
Answered by a test. Each user get it's own stream data only...

**Comment by nielsbaloe** [comment]
yes indeed. and with a bit of tweaking you can exactly decide which users gets to see what. have fun with it!

________________________________
Van: pwFoo <notifications@github.com>
Verzonden: zaterdag 3 augustus 2019 14:48
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Question about SSE (#4)


Answered by a test. Each user get it's own stream data only...
