### ISSUE TITLE
Question about room functionality

### ISSUE THREAD

**Issue by CarloSperandeo** [nielsbaloe/webrtc-php#6]
Hello, first of all, i would thank you for this handy script, very handy for a small project i am working and it doesn't require extra technologies. It just works!
I would ask you a little hint, i wish use it with room logic with use of a private key then 2 users can meet with your script. I tried uncomment your $room variable and give value from querystring but my computers still reach togheter also with different value (while start with value, when working with ajax lost value because don't consider it anymore). How i could make this possible? Have you idea?
Thanks again.

**Comment by nielsbaloe** [comment]
Hi Carlo,
Honestly I never had the room functionality working because I never intended to create rooms, so just enabling that variable won't fully work. You will have to make sure that it is hardwired into everything you do (store/read). I am sure you'll work it out, if it really doesn't than I might be able to help, but it has been a while and you do currently know more than I do as you watched the source recently ;)
Best,
Niels

**Comment by manozzreddy** [comment]
Hi CarloSperandeo,

If you are able to achieve how to use room functionality, can you please help me.

Thanks in Advance

**Comment by CarloSperandeo** [comment]
> Hi CarloSperandeo,
> 
> If you are able to achieve how to use room functionality, can you please help me.
> 
> Thanks in Advance

[index.zip](https://github.com/nielsbaloe/webrtc-php/files/5020999/index.zip)

Hello, i did little change to original index.php file adding token criteria.
From my main script i create and store the token that is like room id and i call script with that parameter, then user that have that parameter will bind to 1 to 1 videochat, before my edit the token doesn't work and was like "anyone could join anyone".
In my scenario and with little needs i just call this index.php into my web app with an iframe (and passing paramenter ?token=number).

Hope it helps, bye.

**Comment by manozzreddy** [comment]
Thank you CarloSperandeo for your response it helped me, in this case I am able to establish another connection only after one connection got established for example(randomly not happening). suppose A user requests with 123 token, B with 346 token, C with 346 token and at last D with 123 token. in this case connection between B and C is happening but A and D is not getting connected,

**Comment by CarloSperandeo** [comment]
You're welcome,
it seems ok, in my case until 2 users will query same token they won't video chat togheter.
In my particular case it work with A and D and B and C togheter and in separate room because of different id.
In my configuration i have setup the script into a custom folder with php and js file with permission to write into folder.
Then my main app will call this php script into iframe with url like site.ext/folder/file.php?token=123 then i make a simple button that refresh the call just by recall the same link into iframe and another for close conversation that destroy id and specific session of my app.
The only logic that is missing is about a cleaner of all temp files generated by php file into video folder but in my case was ok to delete with a cron job (for skip checks on db about what are active or not).

**Comment by manozzreddy** [comment]
Sorry for the above reply, actually it is happening, I did not tested in proper perspective,
Thanks again CarloSperandeo, Bye
