### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getUserMedia' of undefined 

### ISSUE THREAD

**Issue by ppetree** [nielsbaloe/webrtc-php#8]
I'm just delving into webRTC so thanks for sharing this as a getting started point.

I've downloaded and installed the script on a shared server I used for development.  I set the chmod on the folder and the index.php to 755.

I tried the following:

### domain.com/vchat/index.php
These (being essentially the same) produced the same error in the chrome console:
```
Uncaught TypeError: Cannot read property 'getUserMedia' of undefined at index.php:53
(anonymous) @ index.php:53
```
Of course getUserMedia is on line 68 of the source file index.php but line 53 of the output code.

### domain.com/vchat/index.php?eventSource=test
My suspicion is this is how you're reading the blocks of data from the server and is the closest I have gotten to any form of browser output and what I received was **retry: 1000**  I get nothing in the console. No errors. Nothing. Also no error_log output from the script on the server.  When I use the chrome inspector, the index has nothing other than the stuff for the retry:1000

Also, would you please add a bit more to your readme.md and be more specific about the URL and the chmod settings? 

BTW, thanks for doing this... the project and the help on this issue.  I've been looking for a simple .php based example.  Ideally, I want to be able to stream/record to a .php server - perhaps using cURL as an endpoint?

**Comment by ppetree** [comment]
Ok.  I got that one figured out.  I was lazy and just typed in www.domain.com/vchat and according to the[ mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) that leaves an insecure connection and navigator.mediaDevices will be undefined.  I think this should be in the readme.md as well (unless I missed it!)

Now, on to the next problem:
```
(index):75 Uncaught ReferenceError: url is not defined
    at XMLHttpRequest.xhttp.onreadystatechange ((index):75)
xhttp.onreadystatechange @ (index):75
XMLHttpRequest.send (async)
send @ (index):80
publish @ (index):196
(anonymous) @ (index):100
```
If I go in to index.php and edit the URL to include the entire https://www.domain.com url, I still get the URL error.

Very interestingly, if I refresh the page, I don't get prompted to access the video again BUT it does show the video AND I get the following error:
```
(index):53 Uncaught (in promise) TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': At least one of audio and video must be requested
    at (index):53
(anonymous) @ (index):53
(index):196 sending ws.send: client-call
```

**Comment by nielsbaloe** [comment]
Hi,

That 'Failed to execute 'getUserMedia'' kind of error means that it is unable to get the microphone or the video. I am afraid there is not much I can do about it, you can enable or disable the lines 69 /70 audio:true or video:true, just to disable something temporary.

If you get  'url is not defined', there is a javascript error, my bet. I hate javascript and I wish they had decent scope and class functionality, but that is not there yet. You can replace URL with 'index.php?eventSource=yes' everywhere (line 76 and 93), if the URL is not accessible (for some scope reason I do not know). Please change the URL itsself if file is not called index.php .

I guess you're on your own to figure it out, I am not an expert on WebRTC; you can find a lot of resources on WebRTC itsself so you should be able to get things working with some searching.

I will split this example into three files for clarity, once I have some time (Corona takes up quite some extra time for my regular work).

Best,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Phil Petree <notifications@github.com>
Verzonden: vrijdag 15 mei 2020 21:36
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Uncaught TypeError: Cannot read property 'getUserMedia' of undefined (#8)


Ok. I got that one figured out. I was lazy and just typed in www.domain.com/vchat<http://www.domain.com/vchat> and according to the mdn docs<https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia> that leaves an insecure connection and navigator.mediaDevices will be undefined. I think this should be in the readme.md as well (unless I missed it!)

Now, on to the next problem:

(index):75 Uncaught ReferenceError: url is not defined
    at XMLHttpRequest.xhttp.onreadystatechange ((index):75)
xhttp.onreadystatechange @ (index):75
XMLHttpRequest.send (async)
send @ (index):80
publish @ (index):196
(anonymous) @ (index):100


If I go in to index.php and edit the URL to include the entire https://www.domain.com url, I still get the URL error.

Very interestingly, if I refresh the page, I don't get prompted to access the video again BUT it does show the video AND I get the following error:

(index):53 Uncaught (in promise) TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': At least one of audio and video must be requested
    at (index):53
(anonymous) @ (index):53
(index):196 sending ws.send: client-call

**Comment by ppetree** [comment]
Eventually, I got it to work on one end but never got a conversation between two ends.

Thanks for your help.

**Comment by nielsbaloe** [comment]
Hi Phil,

Ah that is harsh to hear.

Well, I had it eventually working, however the webrtc specs change, and that makes it hard. It is a moving target. Usually it works quite allright with two Chrome browsers talking to each other. I had it working with firefox and chrome on different OSses. Anyway hard to hear and I hope you can get other examples to work.



Met vriendelijke groet,

Niels Gorisse
https://www.verbindendecommunicatie.com  - Certified Trainer with the Center for Nonviolent Communication cnvc.org<https://cnvc.org>
https://www.strohplatz.com

________________________________
Van: Phil Petree <notifications@github.com>
Verzonden: zaterdag 16 mei 2020 15:44
Aan: nielsbaloe/webrtc-php <webrtc-php@noreply.github.com>
CC: nielsbaloe <nielsbaloe@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [nielsbaloe/webrtc-php] Uncaught TypeError: Cannot read property 'getUserMedia' of undefined (#8)


Eventually, I got it to work on one end but never got a conversation between two ends.

Thanks for your help.

**Comment by ppetree** [comment]
Sorry. I don't mean to be harsh.  I tried to get it to work between two chrome browsers. Chrome and safari. Chrome and... I could get a video image on all the screens but nothing between any two browsers.

Don't fret it, every webRTC example I've tried has been a bomb.  Only the paid stuff seems to work.
